CREATE TABLE client(
    id BIGINT AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL,
    active TINYINT DEFAULT 1 NOT NULL,
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,

    PRIMARY KEY (id)
);